### ISSUE TITLE
Express Checkout - DoCapture default amount

### ISSUE THREAD

**Issue by gine** [angelleye/paypal-woocommerce#1175] opened 2018-07-16 18:48 UTC
I use Express Checkout with 'authorization' option, so to catch money i must go in the order page on the BE and choose 'DoCapture'. Here appear an input text where i can write the amount which i want capture but if i dont't write any amount the software capture for me the full amount authorized(default amount).

If i make some refund or i apply some coupon, the amount become less of the original amount. But on capture if i don't write any amount, the software capture every time the original amount.

I think that this is a bug. In fact always happens that who must capture money doesn't remembers to reduce the amount before capture. 

Woocommerce calculate for you the amount so write another time the amount to capture it's bad work flow.

Thanks,
g.

**Comment by angelleye** [comment] 2018-07-16 20:15
Thanks for the feedback!  Do I understand how to reproduce this problem correctly?

- Submit an order.
- Process a partial refund for the order.
- Process another partial refund, but do not fill in any amount.
- The refund will fail, because it will attempt to process a full refund of the original amount instead of the remaining amount open.
- Instead, the system should look at the remaining amount open at that point instead of the original amount.

Please verify that, then we'll take a look and make necessary adjustments.  Thanks!

**Comment by gine** [comment] 2018-07-17 08:34
No.

- Submit an order with a customer
- Process a partial manual refund for the order or apply e coupon.
- Capture the amount without write nothing.
- It will capture the original amount not the value already calculated from woocommerce reduced( -refound or -coupon).

**Comment by angelleye** [comment] 2018-07-17 18:51
I see.  I understand now.  We'll get this added to our backlog and get it addressed in one of our next updates.  Thanks again for the feedback!

**Comment by gine** [comment] 2018-07-18 09:17
you are welcome

**Comment by angelleye** [comment] 2018-08-09 20:25
This has been resolved and will be fixed in the 1.4.15 update coming soon.

**Comment by angelleye** [comment] 2018-08-09 20:26
https://angelleye.atlassian.net/browse/PFW-203

**Closed by angelleye** 2018-08-09 20:25 UTC
