### ISSUE TITLE
Express checkout redirection problem with "Polylang for Woocommerce" plugin

### ISSUE THREAD

**Issue by renarded** [angelleye/paypal-woocommerce#1202] opened 2018-09-04 13:21 UTC
Hi,

When setting up a website with Woocommerce + Paypal for Woocommerce + Polylang for Woocommerce, I get a problem during checkout with Paypal Express.

### The issue - how to reproduce

Install all those 3 plugins

In Polylang settings (Languages > Settings > URL modifications), check "Hide URL language information for default language". In my case default is English (so English pages will start with mywebsite.com/ instead of mywebsite.com/en/), and second language is French (so French pages will start with mywebsite.com/fr/). This setting is important, because the problem is only happening when this option is checked.

Go on the shop, browse with second language (in my case French), add a product to cart, go to checkout page --> everything is fine, still French.

Now, when I use the Paypal Express Checkout functionality, and when I get back to the website to review and finish my order (on checkout page), I always get back to the English page (mywebsite/checkout) instead of the French page (mywebsite/fr/commande)

---

I have reached to the Polylang support, and maybe the problem is due to your plugin not compatible with the "Polylang for Woocommerce" plugin, not just the standard "Polylang" plugin.

Don't hesitate to ask me more details. Thanks!

**Comment by iMansoorAliKhan** [comment] 2018-09-04 14:38
hi @renarded  Thanks for your feedback, we have received your request and added this to our dev. backlog we will run some test for the compatibility of both plugins and if there will be any adjustment required in our plugin we will be happy to do that in a future release.

Thanks again!

**Comment by renarded** [comment] 2018-09-04 15:37
Hi @iMansoorAliKhan, thanks for your fast reply. 

I'll then wait for the fix in a future release. Please let me know when this is solved. Thanks!

**Comment by iMansoorAliKhan** [comment] 2018-09-04 15:39
Sure, As we have moved to Jira so I have created a relevant ticket in the system. Closing this ticket but will update you once this perticular issue will be addressed.
Thanks!

**Closed by iMansoorAliKhan** 2018-09-04 15:39 UTC
Labels: moved to jira

**Comment by iMansoorAliKhan** [comment] 2018-09-05 10:30
@renarded  can you please provide me polylang for woocommerce plugin .zip so that we could run some test ?

**Comment by renarded** [comment] 2018-09-05 12:07
@iMansoorAliKhan I've sent you the plugin archive on the email address I found on your github profile.

**Comment by angelleye** [comment] 2018-09-09 23:01
@renarded Per our testing it seems the problem is that Polygon is not correctly handling the `api_request_url` function that is used in WooCommerce.  We could make some adjustments on our end to work-around that, but in our opinion the better fix would be for them to make their plugin compatible with that since WC uses it.

You want to circle back with them and get their thoughts on that?

**Comment by Chouby** [comment] 2018-09-10 14:05
@angelleye Polylang for WooCommerce developer here. Could you please provide more details on why you think we do not handle correcly `api_request_url()` ? The plugin works well with the Paypal gateway provided with WooCommerce.

**Comment by kcppdevelopers** [comment] 2018-09-17 04:31
@angelleye  @Chouby 

https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L613

I have used **api_request_url** function for WooCoomerce plugin and it's always return default language URL when install Polylang for WooCommerce. It should return current active language URL.

**Comment by Chouby** [comment] 2018-09-18 13:11
I intentionally don't filter `api_request_url()` as it may break some other plugins (especially other payment gateways). 
I see that the request to `mywebsite/checkout` is sent by www.paypalobjects.com. Where do you evaluate the checkout url and how do you send it to www.paypalobjects.com?

**Comment by angelleye** [comment] 2018-09-18 15:37
@kcppdevelopers Please see @Chouby's feedback and question here...
