### ISSUE TITLE
Payment Action at product Level

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/paypal-woocommerce#954] opened 2017-12-06 08:32 UTC
> I have one new product I'm introducing, and I'd like to do it as a pre-order. I might be missing a way to do this: I'd like to have just that one product processed as an Authorization, not as a Sale. I would could manually capture those sales from my manager.paypal.com dashboard.
https://www.angelleye.com/support/scp/tickets.php?id=1644

**Comment by angelleye** [comment] 2017-12-28 05:47
Right now we have an option in our gateway settings where people can choose whether or not to submit orders as Authorization or Sale.  We need to add this as a product-level option similar to our options for "No Shipping Required", "Enable Express Checkout", "Enable Billing Agreement", etc.

This will also need to go in our Bulk Updater tool so people can easily enable/disable this for multiple products at once.

We need to be very careful with this because we do not want this change to cause problems with existing sites.  This should be a new feature that allows people to enable/adjust at the product level, but if it hasn't been set there then the general gateway option should take affect.

**Comment by angelleye** [comment] 2017-12-28 05:59
This is a duplicate of #642 where some more feedback from a user is provided.

**Closed** 2018-06-06 20:28 UTC
Labels: duplicate, enhancement, feature request, moved to jira
