### ISSUE TITLE
id was called incorrectly. Order properties should not be accessed directly.

### ISSUE THREAD

**Issue by nathanhannig** [angelleye/paypal-woocommerce#1299] opened 2019-03-18 22:51 UTC
I am receiving this error in logs
`[18-Mar-2019 21:49:54 UTC] id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->process_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->do_payment, WC_Gateway_PayPal_Pro_PayFlow_AngellEYE->save_payment_token, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

I believe the issue is in file `\paypal-for-woocommerce\classes\wc-gateway-paypal-pro-payflow-angelleye.php`

The function doesn't check for Wordpress version like it does in many other files and instead use get_id()
```
public function save_payment_token($order, $payment_tokens_id) {
    // Store source in the order
    if (!empty($payment_tokens_id)) {
        update_post_meta($order->id, '_payment_tokens_id', $payment_tokens_id);
    }
}
```

**Comment by angelleye** [comment] 2019-03-18 22:53
Thanks for the feedback.  I'll get this added to our backlog and we'll see if we can reproduce it resolve it ASAP!

**Comment by angelleye** [comment] 2019-03-18 22:54
Is this a warning which allows the transactions and everything to work as expected, or is this a failure which is causing payments to fail?

**Comment by kcppdevelopers** [comment] 2019-03-19 04:24
@angelleye 

This is just warning which allows the transactions and everything to work as expected. but also add deprecated notice in log file

**Comment by angelleye** [comment] 2019-03-26 06:42
@nathanhannig  We have resolved this PHP notice.  An update will be released soon.

Please make sure you have our [Updater plugin](https://www.angelleye.com/product/angelleye-helper-wordpress-updater/) installed for notices and automated updates going forward.

This is required because we are moving all of our plugins to our own hosting instead of the WordPress directory.

Let me know if you have any questions or concerns about that.  Thanks!

**Closed by angelleye** 2019-03-26 06:42 UTC
